{{- if ((.Values.sessionServer).ingress).enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gitlab-runner.server-session-service-name" . }}-ingress
  {{- if .Values.sessionServer.ingress.annotations }}
  annotations:
    {{- toYaml .Values.sessionServer.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.sessionServer.ingress.className }}
  rules:
    - host: {{ .Values.sessionServer.publicIP }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "gitlab-runner.server-session-service-name" . }}
                port:
                  number: {{ include "gitlab-runner.server-session-external-port" .}}
  {{- $valuesYAMLContext := . }}
  {{- with .Values.sessionServer.ingress.tls }}
  tls:
    {{- range . }}
    - hosts:
        - {{ $valuesYAMLContext.Values.sessionServer.publicIP }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
