apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: static-pool
        auto-assign: false
        protocol: layer2
        addresses:
        - 192.168.83.20/32
      - name: dynamic-pool
        protocol: layer2
        addresses:
        - 192.168.83.75-192.168.83.90
