clair:
  database:
    type: pgsql
    options:
      source: "{{ template "harbor.database.clair" . }}"
      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384
  api:
    # API server port
    port: {{ .Values.clair.server.containerPorts.api }}
    healthport: {{ .Values.clair.server.containerPorts.health }}
    # Deadline before an API request will respond with a 503
    timeout: 300s
  updater:
    interval: {{ .Values.clair.updatersInterval }}
