#
#   Kubernetes Local Persistent Volume
#
#   Verify the following values:
#
#     StorageClass:
#     Capacity:
#     AccessMode:
#
#   Command to execute inside the node that holds the local storage:
#
#     sudo cs-lvmserv.sh -m create -d /srv/nextcloud-mariadb
#


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nextcloud-mariadb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-mariadb
  local:
    path: /srv/nextcloud/data/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-mod-n1
