apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: iot-studio-mosquitto-configinc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: iot-studio-mosquitto-configinc
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iot-studio-mosquitto-configinc
  local:
    path: /srv/iot-studio-mosquitto/data/configinc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-mod-n1
