#
#   cskygen configuration values file
#
#   Copyright © 2021 cSkyLab.com
#

# 
#   Command:
#
#   cskygen create -t ../tpl-cskylab/k8s-ingress-nginx -d ../cs-pro/k8s-pro/ingress-nginx -f k8s-pro-ingress-nginx
#

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-pro

namespace:
  ## k8s namespace name
  name: ingress-nginx

ingressnginx:
  ## LoadBanancer IP static address
  ## Must be previously configured in MetalLB
  loadbalancerip: 192.168.83.20
