{{- if eq (include "gitlab.gitaly.includeInternalResources" $) "true" -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
{{ include (print $.Template.BasePath "/_pdb_spec.yaml") . }}
{{- end -}}
