{{- $sharedSecretValues := index .Values "shared-secrets" -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "shared-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "shared-secrets.name" . }}
    chart: shared-secrets-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
{{- if and $sharedSecretValues.enabled (not .Values.global.operator.enabled) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "patch"]
