{{- $sharedSecretValues := index .Values "shared-secrets" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "shared-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "shared-secrets.name" . }}
    chart: shared-secrets-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
{{- if and $sharedSecretValues.enabled (not .Values.global.operator.enabled) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "shared-secrets.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "shared-secrets.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
