{{- if and .Values.core.configOverwriteJson (not .Values.core.configOverwriteJsonSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config-override" (include "harbor.core" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: core
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  overrides.json: {{ include "common.tplvalues.render" ( dict "value" .Values.core.configOverwriteJson "context" $ ) | b64enc | quote }}
{{- end }}
