{{- if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.clair" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: clair
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: clair
      port: 6060
    - name: health
      port: 6061
    - name: adapter
      port: {{ include "harbor.clairAdapter.servicePort" . }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: clair
{{- end }}
