## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
global:
  postgresql:
    imageRegistry: harbor.cskylab.net/dockerhub

## Bitnami PostgreSQL image version
## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
##
image:
  repository: bitnami/postgresql
  tag: 12.7.0

## PostgreSQL data Persistent Volume Storage Class
persistence:
  storageClass: gitlab-postgresql
  accessMode: ReadWriteOnce
  size: 8Gi

## PostgreSQL password using existing secret
existingSecret: gitlab-postgresql-password

## Create a database
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run
##
postgresqlDatabase: gitlabhq_production
