apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.portal" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if  (eq .Values.ingress.core.controller "gce") }}
  type: NodePort
  {{- end }}
  ports:
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}
      port: {{ ternary .Values.portal.service.ports.https .Values.portal.service.ports.http .Values.internalTLS.enabled }}
      targetPort: {{ ternary "https" "http" .Values.internalTLS.enabled }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
