{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.exporter" . }}-envvars
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: exporter
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  HARBOR_REDIS_URL: {{ include "harbor.redisForJobservice" . | b64enc | quote }}
{{- end }}
