annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.4.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.x.x
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: Harbor is an an open source trusted cloud native registry project that
  stores, signs, and scans content
home: https://github.com/bitnami/charts/tree/master/bitnami/harbor
icon: https://bitnami.com/assets/stacks/harbor-core/img/harbor-core-stack-220x234.png
keywords:
- docker
- registry
- vulnerability
- scan
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: harbor
sources:
- https://github.com/bitnami/bitnami-docker-harbor-core
- https://github.com/bitnami/bitnami-docker-harbor-portal
- https://github.com/bitnami/bitnami-docker-harbor-jobservice
- https://github.com/bitnami/bitnami-docker-harbor-registry
- https://github.com/bitnami/bitnami-docker-harbor-registryctl
- https://goharbor.io/
version: 11.1.0
