annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.6.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Harbor is an open source trusted cloud-native registry to store, sign,
  and scan content. It adds functionalities like security, identity, and management
  to the open source Docker distribution.
home: https://github.com/bitnami/charts/tree/main/bitnami/harbor
icon: https://bitnami.com/assets/stacks/harbor-core/img/harbor-core-stack-220x234.png
keywords:
- docker
- registry
- vulnerability
- scan
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: harbor
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/harbor-core
- https://github.com/bitnami/containers/tree/main/bitnami/harbor-portal
- https://github.com/bitnami/containers/tree/main/bitnami/harbor-jobservice
- https://github.com/bitnami/containers/tree/main/bitnami/harbor-registry
- https://github.com/bitnami/containers/tree/main/bitnami/harbor-registryctl
- https://goharbor.io/
version: 16.0.4
