#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-metallb-system
_tpldescription: MetalLB load-balancer for bare metal Kubernetes clusters
_tplversion: 22-12-19

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name (mandatory)
  name: metallb-system

## MetalLB static and dynamic ip addresses pools
metallb:
  staticpooladdr: 
    - 192.168.82.20/32  # k8s-ingress
    - 192.168.82.21/32  # mosquitto iot-studio
  dynamicpooladdr: 
    - 192.168.82.75-192.168.82.90   # Auto assigned
  