#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-hello
_tpldescription: Kubernetes hellow world app
_tplversion: 909-909-909

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: hello
    ## Service domain name
  domain: cskylab.net

publishing:
  ## External url
  url: hello.cskylab.net

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub
