#
#   k8s mod: hello-kubernetes 
#
#     Example app based on paulbouwer/hello-kubernetes
#     Published at https://{{ .publishing.url }}
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .namespace.name }}
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .certificate.clusterissuer }}
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # cert-manager.io/cluster-issuer: letsencrypt

spec:
  rules:
  - host: {{ .publishing.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-kubernetes-svc
            port:
              number: 80
  tls:
  - hosts:
      - {{ .publishing.url }}
    secretName: hello-kubernetes-tls

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .namespace.name }}
  name: hello-kubernetes-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .namespace.name }}
  name: hello-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: {{ .registry.proxy }}/paulbouwer/hello-kubernetes:1.9
        resources:
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Welcome to cSkyLab k8s cluster!
