#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: cs-miniostalone
_tpldescription: MinIO standalone
_tplversion: 22.02.28

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: miniostalone
  ## Service domain name
  domain: cskylab.net

publishing:
  ## API url
  url: miniostalone.cskylab.net
  ## Console url
  console_url: miniostalone-console.cskylab.net

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

credentials:
  # MinIO root user credentials
  minio_accesskey: "admin"
  minio_secretkey: "NoFear21"

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub

restic:
  ## Restic password is mandatory to access repository
  password: 'NoFear21'

  ## Restic repositories can be located in local paths, sftp paths and s3 buckets
  ## Local path example:
  # repo: '/srv/restic/miniostalone'
  ## S3 example:
  # repo: 's3:https://backup.cskylab.net/restic/miniostalone'
  ## sftp example:
  repo: 'sftp:kos@kvm-main.cskylab.net:/media/data/restic/miniostalone'
  
  ## S3 Bucket access and secret keys must be specified for S3 located repositories
  aws_access: 'restic_rw'
  aws_secret: 'iZ6Qpx1WiqmXXoXKxBxhiCMKWCsYOrgZKr'


## Local storage PV's node affinity (Configured in pv*.yaml)
localpvnodes:    # (k8s node names)
  all_pv: k8s-mod-n1
localrsyncnodes: # (k8s node names)
  all_pv: k8s-mod-n2
