#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-miniostalone
_tpldescription: MinIO standalone
_tplversion: 22-08-21

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: miniostalone
  ## Service domain name
  domain: cskylab.net

publishing:
  ## API url
  url: miniostalone.mod.cskylab.net
  ## Console url
  console_url: miniostalone-console.cskylab.net

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

credentials:
  # MinIO root user credentials
  minio_accesskey: "admin"
  minio_secretkey: "NoFear21"

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub

## Local storage PV's node affinity (Configured in pv*.yaml)
localpvnodes:    # (k8s node names)
  all_pv: k8s-mod-n1
  # k8s nodes domain name
  domain: cskylab.net
  # k8s nodes local administrator
  localadminusername: kos
localrsyncnodes: # (k8s node names)
  all_pv: k8s-mod-n2
  # k8s nodes domain name
  domain: cskylab.net
  # k8s nodes local administrator
  localadminusername: kos
