#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-harbor
_tpldescription: Harbor opensource registry
_tplversion: 23-11-24

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: harbor
  ## Service domain name
  domain: cskylab.net

publishing:
  ## External url
  url: harbor.cskylab.net
  ## Password for administrative user
  password: 'NoFear21'

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

## Local storage PV's node affinity (Configured in pv*.yaml)
localpvnodes:    # (k8s node names)
  all_pv: k8s-mod-n1
  # k8s nodes domain name
  domain: cskylab.net
  # k8s nodes local administrator
  localadminusername: kos
localrsyncnodes: # (k8s node names)
  all_pv: k8s-mod-n2
  # k8s nodes domain name
  domain: cskylab.net
  # k8s nodes local administrator
  localadminusername: kos
