#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-gitlab
_tpldescription: Gitlab DevOps platform
_tplversion: 22-08-21

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: gitlab
  ## Service domain name
  domain: cskylab.net

publishing:
  ## External url
  url: gitlab.cskylab.net
  ## Password for administrative user
  password: "NoFear21"

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

## Keycloak issuer and secret must be previously configured in Keycloak
keycloak:
  issuer: "https://keycloak.cskylab.net/auth/realms/cskylab"
  secret: "5edffd1e-c3ab-47d3-a32e-b38a4977d6d3"

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub

## Local storage PV's node affinity (Configured in pv*.yaml)
localpvnodes:    # (k8s node names)
  all_pv: k8s-mod-n1
  # k8s nodes domain name
  domain: cskylab.net
  # k8s nodes local administrator
  localadminusername: kos
localrsyncnodes: # (k8s node names)
  all_pv: k8s-mod-n2
  # k8s nodes domain name
  domain: cskylab.net
  # k8s nodes local administrator
  localadminusername: kos
