apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.jobservice" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: jobservice
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}
      port: {{ ternary .Values.jobservice.service.ports.https .Values.jobservice.service.ports.http .Values.internalTLS.enabled }}
      targetPort: {{ ternary "https" "http" .Values.internalTLS.enabled }}
    {{- if .Values.metrics.enabled }}
    - name: http-metrics
      port: {{ .Values.jobservice.service.ports.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: jobservice
