apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: iot-edge-mosquitto-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: iot-edge-mosquitto-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iot-edge-mosquitto-data
  local:
    path: /srv/iot-edge-shard1/data/iot-edge/mosquitto/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-pro-n1
