# The number of replicas to create (has no effect if autoscaling enabled)
replicas: 1

image:
  # The Keycloak image repository
  repository: quay.io/keycloak/keycloak
  # Overrides the Keycloak image tag whose default is the chart appVersion
  tag: "26.0.6"
  # Overrides the Keycloak image tag with a specific digest
  digest: ""
  # The Keycloak image pull policy
  pullPolicy: IfNotPresent

# Additional init containers, e. g. for providing custom themes
extraInitContainers: |
  - name: keycloak-theme-provider
    image: {{ .registry.private }}/keycloak-theme-provider:stable
    imagePullPolicy: Always
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying themes..."
        cp -R /themes/bootstrap-mod-keycloak theme1  
        cp -R /themes/bootstrap-mod-nextcloud theme2 
        cp -R /themes/bootstrap-mod-gitlab theme3
        cp -R /themes/bootstrap-pub-keycloak theme4  
        cp -R /themes/bootstrap-pub-nextcloud theme5 
        cp -R /themes/bootstrap-pub-gitlab theme6     
    volumeMounts:
      - name: theme1
        mountPath: /theme1/bootstrap-mod-keycloak
      - name: theme2
        mountPath: /theme2/bootstrap-mod-nextcloud
      - name: theme3
        mountPath: /theme3/bootstrap-mod-gitlab
      - name: theme4
        mountPath: /theme4/bootstrap-pub-keycloak
      - name: theme5
        mountPath: /theme5/bootstrap-pub-nextcloud
      - name: theme6
        mountPath: /theme6/bootstrap-pub-gitlab        


# Additional environment variables for Keycloak
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: keycloak
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "{{ .publishing.password }}"
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ .namespace.name }}-headless
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djava.awt.headless=true

# Add additional volumes, e. g. for custom themes
extraVolumes: |
  - name: theme1
    emptyDir: {}
  - name: theme2
    emptyDir: {}
  - name: theme3
    emptyDir: {}
  - name: theme4
    emptyDir: {}
  - name: theme5
    emptyDir: {}
  - name: theme6
    emptyDir: {}

# Add additional volumes mounts, e. g. for custom themes
extraVolumeMounts: |
  - name: theme1
    mountPath: /opt/keycloak/themes/bootstrap-mod-keycloak
  - name: theme2
    mountPath: /opt/keycloak/themes/bootstrap-mod-nextcloud
  - name: theme3
    mountPath: /opt/keycloak/themes/bootstrap-mod-gitlab
  - name: theme4
    mountPath: /opt/keycloak/themes/bootstrap-pub-keycloak
  - name: theme5
    mountPath: /opt/keycloak/themes/bootstrap-pub-nextcloud
  - name: theme6
    mountPath: /opt/keycloak/themes/bootstrap-pub-gitlab    

## Overrides the default entrypoint of the Keycloak container
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"

ingress:
  # If `true`, an Ingress is created
  enabled: true
  # The Service port targeted by the Ingress
  servicePort: http
  # Ingress annotations
  annotations:
    ## Resolve HTTP 502 error using ingress-nginx:
    ## See https://www.ibm.com/support/pages/502-error-ingress-keycloak-response
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .certificate.clusterissuer }}

  # Additional Ingress labels
  labels: {}
   # List of rules for the Ingress
  rules:
    -
      # Ingress host
      host: '{{ .publishing.url }}'
      # Paths for the host
      paths:
        - path: /
          pathType: Prefix
  # TLS configuration
  tls:
    - hosts:
        - '{{ .publishing.url }}'
      secretName: "tls-keycloak"

dbchecker:
  enabled: true
  image:
    # Docker image used to check Database readiness at startup
    repository: {{ .registry.proxy }}/library/busybox

database:
  # E.g. dev-file, dev-mem, mariadb, mssql, mysql, oracle or postgres
  vendor: postgres
  hostname: postgresql
  port: 5432
  database: keycloak
  username: dbusername
  password: {{ .publishing.password }}
