{{- if .Values.chartmuseum.enabled }}
{{- if .Values.persistence.enabled }}
{{- if and (not .Values.persistence.persistentVolumeClaim.chartmuseum.existingClaim) (eq .Values.persistence.imageChartStorage.type "filesystem") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "harbor.chartmuseum" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: chartmuseum
  annotations:
    {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.persistence.persistentVolumeClaim.chartmuseum.annotations }}
    {{- toYaml .Values.persistence.persistentVolumeClaim.chartmuseum.annotations | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.persistentVolumeClaim.chartmuseum.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.persistentVolumeClaim.chartmuseum.size }}
  {{- if .Values.persistence.persistentVolumeClaim.chartmuseum.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.persistentVolumeClaim.chartmuseum.selector "context" $) | nindent 2 }}
  {{- end }}
  {{- include "common.storage.class" ( dict "persistence" .Values.persistence.persistentVolumeClaim.chartmuseum "global" .Values.global ) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
