annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: 2.0.14
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
description: Eclipse Mosquitto - An open source MQTT broker
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/mosquitto
icon: https://raw.githubusercontent.com/eclipse/mosquitto/master/logo/mosquitto-logo-min.svg
keywords:
- mosquitto
- MQTT
- eclipse-iot
kubeVersion: '>=1.16.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: mosquitto
sources:
- https://github.com/eclipse/mosquitto
version: 4.8.2
