# Configure an ACME Issuer in cert-manager. Only used if global.ingress.configureCertmanager is true.
server: https://acme-v02.api.letsencrypt.org/directory

# Provide an email to associate with your TLS certificates
# email:

rbac:
  create: true

resources:
  requests:
    cpu: 50m

# Priority class assigned to pods
priorityClassName: ""

containerSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: [ "ALL" ]

common:
  labels: {}

useNewIngressForCerts: false
