#cloud-config
#
# Ref.: https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting
#
hostname: k8s-mod-n3
# Change domain name as needed
fqdn: k8s-mod-n3.cskylab.net
manage_etc_hosts: true
users:
  - name: kos
    sudo: ALL=(ALL) NOPASSWD:ALL
    primary_group: kos
    groups: adm, cdrom, sudo, dip, plugdev, lxd
    home: /home/kos
    shell: /bin/bash
    lock_passwd: false
    # ssh-authorized-keys:
    #   - ssh-rsa xxxxxxxxxxx user@machinename
ssh_pwauth: true
chpasswd:
  list: |
     kos:NoFear21
  expire: False
packages:
  - qemu-guest-agent
