apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.core" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: core
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.core.existingSecret }}
  secretKey: {{ include "common.secrets.passwords.manage" (dict "secret" (include "harbor.core" .) "key" "secretKey" "length" 16 "providedValues" (list "core.secretKey") "context" $) }}
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" (include "harbor.core" .) "key" "secret" "length" 16 "providedValues" (list "core.secret") "context" $) }}
  {{- end }}
  {{- if not .Values.core.secretName }}
  {{- $ca := genCA "harbor-token-ca" 365 }}
  tls.crt: {{ include "common.secrets.lookup" (dict "secret" (include "harbor.core" .) "key" "tls.crt" "defaultValue" (coalesce .Values.core.tokenCert $ca.Cert) "context" $) }}
  tls.key: {{ include "common.secrets.lookup" (dict "secret" (include "harbor.core" .) "key" "tls.key" "defaultValue" (coalesce .Values.core.tokenKey $ca.Key) "context" $) }}
  {{- end }}
