apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: '{{ .namespace.name }}-trivy'
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .namespace.name }}-trivy'
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: '{{ .namespace.name }}-trivy'
  local:
    path: '/srv/{{ .namespace.name }}/data/trivy'
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.all_pv }}
