annotations:
  artifacthub.io/changes: |
    - kind: added
      description: allow templates in annotations
      links:
        - name: Github PR
          url: https://github.com/oauth2-proxy/manifests/pull/256
apiVersion: v2
appVersion: 7.7.1
dependencies:
- alias: redis
  condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.4.0
description: A reverse proxy that provides authentication with Google, Github or other
  providers
home: https://oauth2-proxy.github.io/oauth2-proxy/
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
- redis
kubeVersion: '>=1.16.0-0'
maintainers:
- email: cedric@desaintmartin.fr
  name: desaintmartin
- name: tlawrie
- email: nicholas.meves@gmail.com
  name: NickMeves
- email: joel.speed@hotmail.co.uk
  name: JoelSpeed
- email: pierluigi.lenoci@gmail.com
  name: pierluigilenoci
name: oauth2-proxy
sources:
- https://github.com/oauth2-proxy/oauth2-proxy
- https://github.com/oauth2-proxy/manifests
version: 7.8.1
