#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: ubt2004srv-naked
_tpldescription: Ubuntu server 20.04 naked installation
_tplversion: 22.02.28

#
# Values to override
#

## Machine related configuration values
machine:
  hostname: ubt2004srv-naked
  domainname: cskylab.net
  localadminusername: kos
  localadminpassword: "NoFear21"
  timezone: "UTC"
  networkinterface: enp1s0
  ipaddress: 192.168.82.9
  netmask: 24
  gateway4: 192.168.82.1
  searchdomainnames:
    - cskylab.net
  nameservers:
    - 192.168.82.1
  ## Setup directory where configuration files will be injected
  setupdir: "/etc/csky-setup"
  systemlocale: "C.UTF-8"
  systemkeyboard: "us"
  