apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-zoekt.configExternalGatewayMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;

    events {
        use epoll;
    }

    http {
        server {
            {{- if .Values.gateway.tls.certificate.enabled }}
            listen       {{ .Values.gateway.listen.port }} ssl;
            ssl_certificate /etc/ssl/tls.crt;
            ssl_certificate_key /etc/ssl/tls.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            {{- else }}
            listen       {{ .Values.gateway.listen.port }};
            {{- end }}
            server_tokens off;

            proxy_http_version 1.1;

            proxy_set_header Host            $host;
            proxy_set_header X-Forwarded-For $remote_addr;

            resolver {{ .Values.gateway.dnsResolver }};

            set $backend_gateway {{ include "gitlab-zoekt.backendSvcFqdn" . }}:{{ .Values.gateway.listen.port }};

            location = /health {
              return 200;
            }

            location / {
              {{- with .Values.gateway }}
              proxy_pass http{{ .tls.certificate.enabled | ternary "s" "" }}://$backend_gateway;
              {{- end }}
            }

            location ~ ^/nodes/([^/]+)/(.*) {
              {{- with .Values.gateway }}
              set $target_host http{{ .tls.certificate.enabled | ternary "s" "" }}://$1:{{ .listen.port }}/$2;
              {{- end }}

              proxy_pass   $target_host;
            }
        }
    }