#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-minio-operator
_tpldescription: Kubernetes MinIO Operator
_tplversion: 909-909-909

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: minio-operator

publishing:
  ## External url
  url: minio-operator.cskylab.net

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub
