#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-minio-operator
_tpldescription: Kubernetes MinIO Operator
_tplversion: 22.01.07

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: minio-operator

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub
