controller:
  ## Name of the ingress class to route through this controller
  ##
  ingressClass: nginx
  ## DaemonSet or Deployment
  ##
  kind: DaemonSet
  service:
    type: LoadBalancer
    # IPAddress assigned in metallb config
    loadBalancerIP: {{ .ingressnginx.loadbalancerip }}
    externalTrafficPolicy: Local
  # -- This configuration defines if Ingress Controller should allow users to set
  # their own *-snippet annotations, otherwise this is forbidden / dropped
  # when users add those annotations.
  # Global snippets in ConfigMap are still respected
  allowSnippetAnnotations: true

## Gitlab-shell
## If gitlab is installed, you can redirect a tcp port
## to gitlab 
# tcp:
#   22: "<gitlab_namespace_name>/<gitlab_shell_service_name>:22"
