#
#   _values-tpl.yaml
#
#   cskygen template default values file
#

_tplname: k8s-minio-tenant
_tpldescription: Kubernetes MinIO Tenant
_tplversion: 22.01.23

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: minio-tenant

publishing:
  ## External url
  url: minio-tenant.cskylab.net

credentials:
  # MinIO root user credentials
  minio_accesskey: "admin"
  minio_secretkey: "NoFear21"

certificate:
  ## Cert-manager clusterissuer
  clusterissuer: ca-test-internal

registry:
  ## Proxy Repository for Docker
  proxy: harbor.cskylab.net/dockerhub
