#
#   Kubernetes Local Persistent Volume
#
#   Verify the following values:
#
#     StorageClass:
#     Capacity:
#     AccessMode:
#
#   Command to execute inside the node that holds the local storage:
#
#     sudo cs-lvmserv.sh -m create -d /srv/{{ .namespace.name }}
#

# Storage Class

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .namespace.name }}-tenant
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

# MinIO PV's

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s00-d00
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data0-{{ .namespace.name }}-ss-0-0
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s00-d00/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv01_disk01 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s00-d01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data1-{{ .namespace.name }}-ss-0-0
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s00-d01/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv01_disk02 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s00-d02
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data2-{{ .namespace.name }}-ss-0-0
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s00-d02/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv01_disk03 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s00-d03
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data3-{{ .namespace.name }}-ss-0-0
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s00-d03/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv01_disk04 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s01-d00
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data0-{{ .namespace.name }}-ss-0-1
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s01-d00/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv02_disk01 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s01-d01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data1-{{ .namespace.name }}-ss-0-1
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s01-d01/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv02_disk02 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s01-d02
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data2-{{ .namespace.name }}-ss-0-1
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s01-d02/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv02_disk03 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s01-d03
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data3-{{ .namespace.name }}-ss-0-1
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s01-d03/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv02_disk04 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s02-d00
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data0-{{ .namespace.name }}-ss-0-2
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s02-d00/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv03_disk01 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s02-d01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data1-{{ .namespace.name }}-ss-0-2
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s02-d01/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv03_disk02 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s02-d02
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data2-{{ .namespace.name }}-ss-0-2
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s02-d02/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv03_disk03 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s02-d03
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data3-{{ .namespace.name }}-ss-0-2
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s02-d03/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv03_disk04 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s03-d00
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data0-{{ .namespace.name }}-ss-0-3
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s03-d00/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv04_disk01 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s03-d01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data1-{{ .namespace.name }}-ss-0-3
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s03-d01/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv04_disk02 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s03-d02
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data2-{{ .namespace.name }}-ss-0-3
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s03-d02/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv04_disk03 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-s03-d03
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-tenant
  claimRef:
    name: data3-{{ .namespace.name }}-ss-0-3
    namespace: minio-tenant
  local:
    path: /srv/{{ .namespace.name }}-s03-d03/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.srv04_disk04 }}
