{{- if .Values.notary.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-envvars" (include "harbor.notary-server" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: notary
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  server_db_url: {{ include "harbor.database.notaryServer" . | b64enc | quote }}
  signer_db_url: {{ include "harbor.database.notarySigner" . | b64enc | quote }}
{{- end }}
