annotations:
  artifacthub.io/changes: |
    - Allow the release namespace to be overridden (#195)
    - Add missing RBAC rules for customresourcedefinitions (#196)
apiVersion: v2
appVersion: 1.10.4
description: A Helm chart for HAProxy Kubernetes Ingress Controller
home: https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress
icon: https://raw.githubusercontent.com/haproxytech/helm-charts/main/kubernetes-ingress/chart-icon.png
keywords:
- ingress
- haproxy
kubeVersion: '>=1.22.0-0'
maintainers:
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: kubernetes-ingress
sources:
- https://github.com/haproxytech/kubernetes-ingress
type: application
version: 1.32.0
