# QA job to post allure report snapshot as a comment in the MR
e2e-test-report:
  extends:
    # https://gitlab.com/gitlab-org/quality/pipeline-common/-/blob/master/ci/allure-report.yml
    - .generate-allure-report-base
  stage: qa-report
  variables:
    GITLAB_AUTH_TOKEN: $DANGER_GITLAB_API_TOKEN
    ALLURE_PROJECT_PATH: $CI_PROJECT_PATH
    ALLURE_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    ALLURE_RESULTS_GLOB: "gitlab-qa-run-*/**/allure-results"
    ALLURE_JOB_NAME: $QA_RUN_TYPE
  rules:
    - if: '$CI_SERVER_HOST != "gitlab.com"'
      when: never
    - if: '$PIPELINE_TYPE =~ /_MR_PIPELINE$/'
