#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: {{ .registry.proxy }}/nodered/node-red
  # -- image tag
  tag: "3.1.8"
  # -- image pull policy
  # pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://nodered.org/docs/getting-started/docker) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: "{{ .nodered.timezone }}"
  # -- Node.js runtime arguments
  NODE_OPTIONS:
  # -- Setting to `true` starts Node-RED with the projects feature enabled
  NODE_RED_ENABLE_PROJECTS:
  # -- Setting to `true` starts Node-RED in safe (not running) mode
  NODE_RED_ENABLE_SAFE_MODE:
  # -- Location of the flows configuration file.
  # If you set `FLOWS: ""` then the flow file can be set via the `flowFile` property in the `settings.js` file.
  FLOWS:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 1880

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    primary: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: {{ .certificate.clusterissuer }}
      # cert-manager.io/cluster-issuer: letsencrypt-staging
      # cert-manager.io/cluster-issuer: letsencrypt

      ## Ingress annotations for oauth2-proxy
      nginx.ingress.kubernetes.io/auth-url: "https://oauth-{{ .publishing.url }}/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth-{{ .publishing.url }}/oauth2/start?rd=$scheme://$best_http_host$request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      acme.cert-manager.io/http01-edit-in-place: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

    hosts:
      -  # -- Host address. Helm template can be passed.
        host: {{ .publishing.url }}
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name: node-red
              # -- Overrides the service port reference for this path
              port: 1880

    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls:
      - secretName: node-red-tls
        hosts:
          - {{ .publishing.url }}


# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: /data
    storageClass: "{{ .edgename }}-node-red"
    accessMode: ReadWriteOnce
    size: 1Gi
