# Default values for minio-operator.

# operator:
#   image:
#     repository: harbor.cskylab.net/dockerhub/minio/operator

console:
  # image:
  #   repository: harbor.cskylab.net/dockerhub/minio/console
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: ca-test-internal
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # cert-manager.io/cluster-issuer: letsencrypt

    host: minio-operator.mod.cskylab.net
    tls:
    - hosts:
      - minio-operator.mod.cskylab.net
      secretName: minio-operator-tls
