apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .namespace.name }}-node-red
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-node-red
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-node-red
  local:
    path: /srv/{{ .namespace.name }}-node-red/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.all_pv }}
