apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .namespace.name }}-mosquitto-configinc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-mosquitto-configinc
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-mosquitto-configinc
  local:
    path: /srv/{{ .datadirectoryname }}/data/mosquitto/configinc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.all_pv }}
