apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: '{{ .namespace.name }}-dovecot'
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .namespace.name }}-dovecot'
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: '{{ .namespace.name }}-dovecot'
  local:
    path: '/srv/{{ .namespace.name }}/data/dovecot'
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.all_pv }}
