annotations:
  category: Analytics
apiVersion: v2
appVersion: 9.0.5
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Grafana is an open source metric analytics and visualization suite for
  visualizing time series data that supports various types of data sources.
home: https://github.com/bitnami/charts/tree/master/bitnami/grafana
icon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: grafana
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/grafana
- https://grafana.com/
version: 8.0.4
