#
#   Kubernetes Local Persistent Volume
#
#   Verify the following values:
#
#     StorageClass:
#     Capacity:
#     AccessMode:
#
#   Command to execute inside the node that holds the local storage:
#
#     sudo cs-lvmserv.sh -m create -d /srv/{{ .namespace.name }}-postgresql
#


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .namespace.name }}-postgresql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .namespace.name }}-postgresql
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .namespace.name }}-postgresql
  local:
    path: /srv/{{ .namespace.name }}/data/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .localpvnodes.all_pv }}
