{{- if and .Values.rbac.enabled .Values.rbac.serviceaccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceaccount.name }}
  {{- if .Values.rbac.serviceaccount.annotations }}
  annotations:
    {{- toYaml .Values.rbac.serviceaccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
