{{- if eq .Values.exposureType "proxy" }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "harbor.nginx" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: nginx
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  {{- if .Values.nginx.updateStrategy }}
  strategy: {{- toYaml .Values.nginx.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.nginx.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.nginx.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: nginx
      annotations:
        {{- if not .Values.nginx.tls.enabled }}
        checksum/configmap: {{ include (print $.Template.BasePath "/nginx/configmap-http.yaml") . | sha256sum }}
        {{- else }}
        checksum/configmap: {{ include (print $.Template.BasePath "/nginx/configmap-https.yaml") . | sha256sum }}
        {{- end }}
        {{- if (include "harbor.autoGenCertForNginx" .) }}
        checksum/tls-secret: {{ include (print $.Template.BasePath "/nginx/tls-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.nginx.podAnnotations }}
        annotations: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "harbor.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.nginx.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.nginx.podAffinityPreset "component" "nginx" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.nginx.podAntiAffinityPreset "component" "nginx" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nginx.nodeAffinityPreset.type "key" .Values.nginx.nodeAffinityPreset.key "values" .Values.nginx.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nginx.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.priorityClassName }}
      priorityClassName: {{ .Values.nginx.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.nginx.schedulerName }}
      schedulerName: {{ .Values.nginx.schedulerName }}
      {{- end }}
      {{- if .Values.nginx.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.nginx.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.initContainers }}
      initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          image: {{ include "harbor.nginx.image" . }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy | quote }}
          {{- if .Values.nginx.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.nginx.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.nginx.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.nginx.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" .Values.nginx.image.debug | quote }}
            {{- if .Values.nginx.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.nginx.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.nginx.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.nginx.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.nginx.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.nginx.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.nginx.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.nginx.containerPorts.http }}
              name: http
            - containerPort: {{ .Values.nginx.containerPorts.https }}
              name: https
            - containerPort: {{ .Values.nginx.containerPorts.notary }}
              name: notary
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.nginx.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.nginx.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.nginx.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: {{ ternary "https" "http" .Values.nginx.tls.enabled }}
          {{- end }}
          {{- if .Values.nginx.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.nginx.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.nginx.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: {{ ternary "https" "http" .Values.nginx.tls.enabled }}
              scheme: {{ ternary "https" "http" .Values.nginx.tls.enabled  | upper }}
          {{- end }}
          {{- if .Values.nginx.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.nginx.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.nginx.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.nginx.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: {{ ternary "https" "http" .Values.nginx.tls.enabled }}
              scheme: {{ ternary "https" "http" .Values.nginx.tls.enabled  | upper }}
          {{- end }}
          {{- end }}
          {{- if .Values.nginx.resources }}
          resources: {{- toYaml .Values.nginx.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/nginx/conf/nginx.conf
              subPath: nginx.conf
            {{- if .Values.nginx.tls.enabled }}
            - name: certificate
              mountPath: /etc/nginx/cert
            {{- end }}
            {{- if .Values.nginx.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.nginx.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.nginx.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.nginx.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "harbor.nginx" . }}
        {{- if .Values.nginx.tls.enabled }}
        - name: certificate
          secret:
            {{- if .Values.nginx.tls.existingSecret }}
            secretName: {{ .Values.nginx.tls.existingSecret }}
            {{- else }}
            secretName: {{ include "harbor.nginx" . }}
            {{- end }}
        {{- end }}
      {{- if .Values.nginx.extraVolumes }}
      {{- include "common.tplvalues.render" (dict "value" .Values.nginx.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
