{{- if and .Values.global.kas.enabled .Values.metrics.enabled .Values.metrics.podMonitor.enabled -}}
{{- if .Values.metrics.serviceMonitor.enabled }}
{{- fail "Both metrics.serviceMonitor.enabled and metrics.podMonitor.enabled cannot be set to true at the same time within the same subchart." }}
{{- end }}
{{- if eq (include "gitlab.monitoring.enabled" .) "true" -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
  {{- with .Values.metrics.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kas.podSelectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http-metrics
      path: {{ .Values.metrics.path }}
    {{- with .Values.metrics.podMonitor.endpointConfig }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end -}}
{{- end -}}
