{{- if .Values.clair.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.clair" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "conf/clair.yaml") . | b64enc }}
  redis: {{ include "harbor.redisForClairAdapter" . | b64enc }}
  database: {{ include "harbor.database.clair" . | b64enc }}
{{- end }}
