#
#   cskygen configuration values file
#
#   Copyright © 2021 cSkyLab.com
#

# 
#   Command:
#
#   cskygen create -t ../tpl/k8s-ingress-nginx -d ../cs-mod/k8s-mod/ingress-nginx -f k8s-mod-ingress-nginx
#

#
# Values to override
#

## k8s cluster credentials kubeconfig file
kubeconfig: config-k8s-mod

namespace:
  ## k8s namespace name
  name: ingress-nginx

ingressnginx:
  ## LoadBanancer IP static address
  ## Must be previously configured in MetalLB
  loadbalancerip: 192.168.82.20
